version: '2'
volumes:
  nifi:
    external: true
services:
  zoo1:
    image: zookeeper
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-sp:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8010:8080"
    environment:
      - NIFI_PROFILE=nifi-sp
    volumes:
      - nifi:/opt/nifi/storage

  nifi-ss:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8410:8443"
    environment:
      - NIFI_PROFILE=nifi-ss
      - NIFI_HOSTNAME=nifi-ss
      - NIFI_LIB_VERSION=1.1.0-SNAPSHOT
    volumes:
      - nifi:/opt/nifi/storage

  nifi-cp:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8020:8080"
    depends_on:
      - zoo1
    environment:
      - NIFI_PROFILE=nifi-cp

  nifi-cp-nodes:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - nifi-cp
    environment:
      - NIFI_PROFILE=nifi-cp

  nifi-cs1:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    ports:
      - "8420:8443"
    depends_on:
      - zoo1
    environment:
      - NIFI_PROFILE=nifi-cs1
      - NIFI_HOSTNAME=nifi-cs1
      - NIFI_CLUSTERNAME=nifi-cs

  nifi-cs2:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - zoo1
    environment:
      - NIFI_PROFILE=nifi-cs2
      - NIFI_HOSTNAME=nifi-cs2
      - NIFI_CLUSTERNAME=nifi-cs

  nifi-cs3:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - zoo1
    environment:
      - NIFI_PROFILE=nifi-cs3
      - NIFI_HOSTNAME=nifi-cs3
      - NIFI_CLUSTERNAME=nifi-cs
