version: '2'

volumes:
  nifi:
    external: true

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  zoo1:
    image: zookeeper
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888

  nifi-cp:
    extends:
      file: ./nifi-container/docker-compose.yml
      service: nifi
    depends_on:
      - zoo1
    environment:
      - NIFI_PROFILE=nifi-cp
      - VIRTUAL_HOST=nifi-cp.local
      - VIRTUAL_PORT=8080

