version: '2'

volumes:
  nifi:
    external: true

services:
  nifi:
    build: .
    image: nifi:1.0.0
    environment:
      - NIFI_LIB_VERSION=1.3.0-vote
    volumes:
      - nifi:/opt/nifi/storage
